local    all          all                                      trust
local    replication all                                      trust
hostssl  all          all                127.0.0.1/32           scram-sha-256
hostssl  all          all                10.72.0.1/32           scram-sha-256
hostssl  replication niffler_colo_repl  10.72.0.1/32           scram-sha-256
hostnossl all         all                0.0.0.0/0              reject
hostnossl all         all                ::/0                   reject
host     all          all                0.0.0.0/0              reject
host     all          all                ::/0                   reject
