#!/usr/sbin/nft -f

flush ruleset

table inet filter {
	chain input {
		type filter hook input priority filter; policy drop;

		iifname "lo" accept
		ct state established,related accept
		ct state invalid drop

		ip protocol icmp accept
		ip6 nexthdr ipv6-icmp accept
		udp sport 67 udp dport 68 accept
		udp sport 547 udp dport 546 accept

		tcp dport { 22, 80, 443 } accept
		udp dport 443 accept
		ip saddr 23.19.228.223 udp dport 51820 accept
	}

	chain forward {
		type filter hook forward priority filter; policy drop;
	}

	chain output {
		type filter hook output priority filter; policy accept;
	}
}
