listen_addresses = '127.0.0.1,10.72.0.5'
port = 55432
max_connections = 100

password_encryption = 'scram-sha-256'
ssl = on
ssl_cert_file = '/etc/postgresql/tls/server.crt'
ssl_key_file = '/etc/postgresql/tls/server.key'
ssl_min_protocol_version = 'TLSv1.2'

shared_buffers = '16GB'
effective_cache_size = '48GB'
maintenance_work_mem = '1GB'
work_mem = '16MB'
huge_pages = try
effective_io_concurrency = 200
random_page_cost = 1.1

wal_level = replica
wal_compression = on
min_wal_size = '2GB'
max_wal_size = '8GB'
checkpoint_completion_target = 0.9
fsync = on
full_page_writes = on
synchronous_commit = on

log_destination = 'stderr'
logging_collector = off
log_checkpoints = on
log_lock_waits = on
log_min_duration_statement = 1000
deadlock_timeout = '1s'
timezone = 'UTC'
