// 指标名称与属性对齐 codex2api PR #666（8d959db）；数值由 Niffler 独立生成。
pub(super) const METRICS: &[(&str, &str, &str, &str)] = &[
    ("codex.process.start", "sum", "", "originator"),
    ("codex.sqlite.init.count", "sum", "", "db,error,originator,phase,status"),
    ("codex.sqlite.init.duration_ms", "histogram", "ms", "db,error,originator,phase,status"),
    ("codex.app_server.codex_home.size_bytes", "histogram", "", "compression_enabled,directory"),
    ("codex.remote_models.fetch_update.duration_ms", "histogram", "ms", ""),
    ("codex.plugins.loaded_cache.event", "sum", "", "event"),
    ("codex.remote_models.load_cache.duration_ms", "histogram", "ms", ""),
    ("codex.plugins.loaded_cache.wait.duration_ms", "histogram", "ms", ""),
    ("codex.plugins.loaded_cache.load.duration_ms", "histogram", "ms", ""),
    ("codex.plugins.loaded_cache.request", "sum", "", "outcome"),
    ("codex.mcp.protocol_discovery", "sum", "", "mode,outcome,server_kind"),
    ("codex.mcp.protocol_discovery.duration_ms", "histogram", "ms", "mode,outcome,server_kind"),
    ("codex.mcp.tools.fetch_uncached.duration_ms", "histogram", "ms", "trigger"),
    ("codex.mcp.tools.list.duration_ms", "histogram", "ms", "cache"),
    ("codex.apps.installed.duration_ms", "histogram", "ms", "force_refresh,outcome,path,refresh,reload,retained_previous_snapshot"),
    ("codex.apps.installed.response_bytes", "histogram", "", "path"),
    ("codex.apps.installed.connector_count", "histogram", "", "path"),
    ("codex.apps.installed.tool_count", "histogram", "", "path"),
    ("codex.apps.snapshot.age_ms", "histogram", "ms", "observation,path"),
    ("codex.apps.read.duration_ms", "histogram", "ms", "include_tools"),
    ("codex.sqlite.logs.write.count", "sum", "", "error,originator,status"),
    ("codex.sqlite.logs.write.duration_ms", "histogram", "ms", "error,originator,status"),
    ("codex.sqlite.logs.write.bytes", "histogram", "", "error,originator,status"),
    ("codex.sqlite.logs.write.entries", "histogram", "", "error,originator,status"),
    ("codex.sqlite.logs.write.max_entry_bytes", "histogram", "", "error,originator,status"),
    ("codex.mcp.tools.cache_write.duration_ms", "histogram", "ms", "status"),
    ("codex.mcp.tools.cache_publish.duration_ms", "histogram", "ms", "result,source"),
    ("codex.apps.refresh.duration_ms", "histogram", "ms", "path,trigger"),
    ("codex.feature.state", "sum", "", "app.version,auth_mode,feature,model,originator,service_name,session_source,value"),
    ("codex.thread.started", "sum", "", "app.version,auth_mode,is_git,model,originator,service_name,session_source"),
    ("codex.shell_snapshot.duration_ms", "histogram", "ms", "app.version,auth_mode,model,originator,session_source,success,version"),
    ("codex.shell_snapshot", "sum", "", "app.version,auth_mode,failure_reason,model,originator,session_source,success,version"),
    ("codex.startup.phase.duration_ms", "histogram", "ms", "app.version,auth_mode,model,originator,phase,service_name,session_source,status"),
    ("codex.websocket.request", "sum", "", "app.version,auth_mode,model,originator,service_name,session_source,success"),
    ("codex.websocket.request.duration_ms", "histogram", "ms", "app.version,auth_mode,model,originator,service_name,session_source,success"),
    ("codex.rollout_compression.materialize", "sum", "", "outcome"),
    ("codex.websocket.event", "sum", "", "app.version,auth_mode,kind,model,originator,service_name,session_source,success"),
    ("codex.websocket.event.duration_ms", "histogram", "ms", "app.version,auth_mode,kind,model,originator,service_name,session_source,success"),
    ("codex.startup_prewarm.duration_ms", "histogram", "ms", "app.version,auth_mode,model,originator,service_name,session_source,status"),
    ("codex.startup_prewarm.age_at_first_turn_ms", "histogram", "ms", "app.version,auth_mode,model,originator,service_name,session_source,status"),
    ("codex.thread.skills.enabled_total", "histogram", "", "app.version,auth_mode,catalog_surface,model,originator,service_name,session_source"),
    ("codex.thread.skills.kept_total", "histogram", "", "app.version,auth_mode,catalog_surface,model,originator,service_name,session_source"),
    ("codex.thread.skills.truncated", "histogram", "", "app.version,auth_mode,catalog_surface,model,originator,service_name,session_source"),
    ("codex.thread.skills.description_truncated_chars", "histogram", "", "app.version,auth_mode,catalog_surface,model,originator,service_name,session_source"),
    ("codex.skills.shadow_selection", "sum", "", "candidate_set_truncated,method,query_script,query_truncated,status"),
    ("codex.skills.shadow_selection.duration_ms", "histogram", "ms", "candidate_set_truncated,method,query_script,query_truncated,status"),
    ("codex.skills.shadow_selection.catalog_entries", "histogram", "", "candidate_set_truncated,method,query_script,query_truncated,status"),
    ("codex.skills.shadow_selection.selected_entries", "histogram", "", "candidate_set_truncated,method,query_script,query_truncated,status"),
    ("codex.skills.shadow_selection.query_terms", "histogram", "", "candidate_set_truncated,method,query_script,query_truncated,status"),
    ("codex.skills.shadow_selection.reduction_bps", "histogram", "", "candidate_set_truncated,method,query_script,query_truncated,status"),
    ("codex.turn.ttft.duration_ms", "histogram", "ms", "app.version,auth_mode,model,originator,service_name,session_source"),
    ("codex.turn.ttfm.duration_ms", "histogram", "ms", "app.version,auth_mode,model,originator,service_name,session_source"),
    ("codex.responses_api_overhead.duration_ms", "histogram", "ms", "app.version,auth_mode,model,originator,service_name,session_source"),
    ("codex.responses_api_inference_time.duration_ms", "histogram", "ms", "app.version,auth_mode,model,originator,service_name,session_source"),
    ("codex.responses_api_engine_iapi_tbt.duration_ms", "histogram", "ms", "app.version,auth_mode,model,originator,service_name,session_source"),
    ("codex.turn.e2e_duration_ms", "histogram", "ms", "app.version,auth_mode,model,originator,service_name,session_source"),
    ("codex.turn.network_proxy", "sum", "", "active,app.version,auth_mode,model,originator,service_name,session_source,tmp_mem_enabled"),
    ("codex.turn.tool.call", "histogram", "", "app.version,auth_mode,model,originator,service_name,session_source,tmp_mem_enabled"),
    ("codex.turn.memory", "sum", "", "app.version,auth_mode,config_use_memories,feature_enabled,has_citations,model,originator,read_allowed,service_name,session_source"),
    ("codex.turn.unified_exec.running_processes", "sum", "", "app.version,auth_mode,model,originator,service_name,session_source"),
    ("codex.windows_mxc.available", "sum", "", "available"),
    ("codex.tool.unified_exec", "sum", "", "app.version,auth_mode,model,originator,session_source,tty"),
    ("codex.hooks.run", "sum", "", "app.version,auth_mode,execution_mode,handler_type,hook_name,model,originator,session_source,source,status"),
    ("codex.hooks.run.duration_ms", "histogram", "ms", "app.version,auth_mode,execution_mode,handler_type,hook_name,model,originator,session_source,source,status"),
    ("codex.external_agent_config.detect", "sum", "", "migration_type"),
    ("codex.rollout.size_bytes", "histogram", "", ""),
];

pub(super) const ATTRIBUTE_DEFAULTS: &[(&str, &str)] = &[
    ("auth_mode", "Chatgpt"),
    ("status", "success"),
    ("success", "true"),
    ("error", "none"),
    ("outcome", "success"),
    ("active", "false"),
    ("available", "true"),
    ("is_git", "false"),
    ("tty", "false"),
    ("cache", "miss"),
    ("compression_enabled", "false"),
    ("execution_mode", "sync"),
    ("handler_type", "mcp_tool"),
    ("hook_name", "Stop"),
    ("source", "plugin"),
    ("migration_type", "config"),
    ("tmp_mem_enabled", "false"),
    ("value", "true"),
    ("candidate_set_truncated", "false"),
    ("catalog_surface", "thread_context"),
    ("config_use_memories", "true"),
    ("db", "state"),
    ("directory", "codex_home"),
    ("event", "clear"),
    ("feature", "hooks"),
    ("feature_enabled", "false"),
    ("failure_reason", "write_failed"),
    ("force_refresh", "false"),
    ("has_citations", "false"),
    ("include_tools", "false"),
    ("kind", "response.completed"),
    ("method", "weighted_lexical_v1"),
    ("mode", "legacy"),
    ("observation", "installed"),
    ("path", "new"),
    ("phase", "open_state"),
    ("query_script", "mixed"),
    ("query_truncated", "false"),
    ("read_allowed", "false"),
    ("refresh", "not_requested"),
    ("reload", "false"),
    ("result", "published"),
    ("retained_previous_snapshot", "false"),
    ("server_kind", "openai_codex_apps"),
    ("trigger", "initial"),
    ("version", "v1"),
];
